### ISSUE TITLE
[Bug]: Record bug

### ISSUE THREAD

**Issue by Blacksquadman1** [Ree6-Applications/Ree6#534]
### Contact Details

blacksquadman1@gamingbaeren.de/Blacksquadman1

### What happened?

I have the error that when I want to make a record, regardless of whether it is self-hosted or with the official ree6, I either don't get a download link or I get a link but no file. I once received a self-hosted file that was 34,604 bytes in size but had no content
[backend.log](https://github.com/Ree6-Applications/Ree6/files/14274380/backend.log)
[bot.log](https://github.com/Ree6-Applications/Ree6/files/14274385/bot.log)

### Version

v3 (Current)

### Relevant log output

```shell
Console output with link

01:44:54 [JDA [0 / 1] AudioConnection Guild: 800333202462867486 Receiving Thread] ERROR n.d.j.i.audio.AudioConnection - There was some random exception while waiting for udp packets 
java.lang.IndexOutOfBoundsException: null
        at java.base/java.nio.Buffer.checkIndex(Buffer.java:749)
        at java.base/java.nio.HeapByteBuffer.getChar(HeapByteBuffer.java:335)
        at net.dv8tion.jda.internal.audio.AudioPacket.<init>(AudioPacket.java:78)
        at net.dv8tion.jda.internal.audio.AudioPacket.<init>(AudioPacket.java:70)
        at net.dv8tion.jda.internal.audio.AudioPacket.decryptAudioPacket(AudioPacket.java:195)
        at net.dv8tion.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:380)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by DxsSucuk** [comment]
This should be fixed with the latest dev version, in case this error still occurs with the latest version let me know!
