### ISSUE TITLE
[Bug]: `/record` isn't working when self-hosting

### ISSUE THREAD

**Issue by jiriks74** [Ree6-Applications/Ree6#563]
### Contact Details

@jiriks74

### What happened?

When self-hosting the record feature isn't working correctly.
I run Ree6 using Pterodactyl and I've set the recording url to my dashboard:
![image](https://github.com/Ree6-Applications/Ree6/assets/54378412/4d82cea6-f359-4b93-9958-c4769dd7a281)

However when I create a new recording it stil points to `cp.ree6.de`. I found out that in `config.yml` it's still set to default:
```
        record: https://ree6.example.com/external/recording/
        recording: https://cp.ree6.de/external/recording
```

Even after changing this I get the correct link but the recording isn't found:
![image](https://github.com/Ree6-Applications/Ree6/assets/54378412/9d3141af-a8d9-4e36-b1a0-f3f847090136)

### Version

v3 (Current)

### Relevant log output

```shell
02:43:51 [JDA [0 / 1] AudioConnection Guild: 574287666955157534 Receiving Thread] ERROR n.d.j.i.audio.AudioConnection - There was some random exception while waiting for udp packets 
java.lang.IndexOutOfBoundsException: null
        at java.base/java.nio.Buffer.checkIndex(Buffer.java:749)
        at java.base/java.nio.HeapByteBuffer.getChar(HeapByteBuffer.java:335)
        at net.dv8tion.jda.internal.audio.AudioPacket.<init>(AudioPacket.java:78)
        at net.dv8tion.jda.internal.audio.AudioPacket.<init>(AudioPacket.java:70)
        at net.dv8tion.jda.internal.audio.AudioPacket.decryptAudioPacket(AudioPacket.java:195)
        at net.dv8tion.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:380)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DxsSucuk** [comment]
Related to Backend not being updated to the latest SQL dependency.

**Comment by DxsSucuk** [comment]
Should be fixed with latest comit.

**Comment by jiriks74** [comment]
Will there be a build or should I build it myself?

**Comment by DxsSucuk** [comment]
The latest Dev build should contain the fix.

**Comment by jiriks74** [comment]
I downloaded a newer Backend from one Action's Artifacts.

I got some permission issues (I think that there should be a catch that sends a message to the admin to allow this permission). But after adding the deafen permission I get this error:

``
01:42:20 [ForkJoinPool.commonPool-worker-24] ERROR d.p.r.commands.interfaces.ICommand - An error occurred while executing the command! 
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Can only deafen members who are currently in a voice channel
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: Can only deafen members who are currently in a voice channel
        at net.dv8tion.jda.internal.entities.GuildImpl.deafen(GuildImpl.java:1605)
        at net.dv8tion.jda.api.entities.Member.deafen(Member.java:809)
        at de.presti.ree6.commands.impl.fun.Record.connectAndRecord(Record.java:72)
        at de.presti.ree6.commands.impl.fun.Record.onPerform(Record.java:47)
        at de.presti.ree6.commands.interfaces.ICommand.lambda$onASyncPerform$0(ICommand.java:35)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 6 common frames omitted
```

Could we please reopen this until it's working?

**Comment by DxsSucuk** [comment]
It should still work, that error just means that it couldn't undeafen since its not yet in a vc. The recording should have still started.

**Comment by DxsSucuk** [comment]
Exception is now fixed so it can be closed again.
